name: CI

on:
    push:
    pull_request:

jobs:
    release:
        if: startsWith(github.ref, 'refs/tags/')
        runs-on: ubuntu-latest
        permissions:
            contents: write
        needs: [fmt, test, bench, examples]
        steps:
            - name: Checkout
              uses: actions/checkout@v4
            - name: Release
              uses: softprops/action-gh-release@v2
              with:
                  draft: true
    fmt:
        runs-on: ubuntu-latest
        permissions:
            contents: write
        steps:
            - name: Checkout
              uses: actions/checkout@v4
            - uses: goto-bus-stop/setup-zig@v2
              with:
                  version: 0.13.0
            - name: fmt
              run: zig fmt --check .
    bench:
        runs-on: ubuntu-latest
        permissions:
            contents: write
        steps:
            - name: Checkout
              uses: actions/checkout@v4
            - uses: goto-bus-stop/setup-zig@v2
              with:
                  version: 0.13.0
            - name: Bench
              run: zig build bench -Doptimize=ReleaseFast
    examples:
        runs-on: ubuntu-latest
        permissions:
            contents: write
        steps:
            - name: Checkout
              uses: actions/checkout@v4
            - uses: goto-bus-stop/setup-zig@v2
              with:
                  version: 0.13.0
            - name: Example
              run: zig build run-demo-example

    test:
        runs-on: ubuntu-latest
        permissions:
            contents: write
        steps:
            - name: Checkout
              uses: actions/checkout@v4
            - uses: goto-bus-stop/setup-zig@v2
              with:
                  version: 0.13.0
            - name: Test
              run: zig build test --summary all
